# Schema for the configuration files of the OpenID Connect module.

openid_connect.settings.accessci:
  type: config_object
  label: 'OpenID Connect accessci settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enable client'
    settings:
      type: mapping
      mapping:
        client_id:
          type: string
          label: 'Client ID'
        client_secret:
          type: string
          label: 'Client secret'
        authorization_endpoint:
          type: string
          label: 'Authorization endpoint'
        token_endpoint:
          type: string
          label: 'Token endpoint'
        userinfo_endpoint:
          type: string
          label: 'Userinfo endpoint'
        requested_scopes:
          type: string
          label: 'Requested scopes'
        login_redirection:
          type: string
          label: 'Target page after login'
